### ISSUE TITLE
Add multi-token support.

### ISSUE THREAD

**Issue by internetztube** [hubertprein/Craft-JwtManager#3]
In the current implementation, the old token gets deleted if you generate a new one. 
https://github.com/hubertprein/Craft-JwtManager/blob/v2/src/services/Jwts.php#L430

What would be your preferred way to implement multi-token support? cp-lightswitch, method parameter, ...?

**Comment by hubertprein** [comment]
My assumption was that, based on the `type` only one can exist for a certain user and its current `device`. That was it was more secure because only one is "going" around, rather than multiple. Could you elaborate a scenario where someone would require a multi-token for a user, with the same `type` and `device`?

**Comment by internetztube** [comment]
I'm currently building on a sales tool for a customer. The requirement is that the tool should run in a Browser and as a Desktop App (Electron).
So if the customer authenticates in the desktop app and then switches to the web app, then the desktop app tokens are invalid.

**Comment by hubertprein** [comment]
Right. Which to me sounds valid, the way it should work. The desktop and web app are separate and should both authenticate for the user. So the user logs in once on both the desktop and web, and then everything should run fine as it should be.

Open for discussion, but if you'd allow otherwise, to me you'd create a security breach. If someone would manage to get your JWT then it doesn't matter on which device or whatever it would be used, you would always be able to login on that account of the user.

You could however, create a `one time login` token (static `TYPE_ONE_TIME_LOGIN`) that you place in the web or desktop app (whichever should be used first) and that way the user will still be able to login immediately without the user's credentials.

Edit:
You got me thinking.. 🤔 Do the desktop and web app result in the same `browser` and `type`? Because if that's the case, then yes, you probably run into issues where the JWT could be deleted when authorized for the second time on one of the two.

**Comment by internetztube** [comment]
They do not result in the same `browser` `type` combo. Apart from the code, I have noticed that only the `browser` `device` combo is checked.

**Comment by internetztube** [comment]
Yes, I run into this issue. In your opinion, would it be reasonable to create an own type for desktop apps?

**Comment by hubertprein** [comment]
A type would require custom code, while you want to use it for login. Probably, a better solution would be to add a custom `device` to the `getDeviceType` function in the `MobileDetect` service. We have to differentiate between `web` and `desktop`. Perhaps a header check which is hopefully different with Electron than a regular web request?

**Comment by internetztube** [comment]
Okay, now I get it. I completely agree with you.

That means it makes no sense for me to fetch a `login` and `refresh` token for the webapp. But now the question is, how can I obtain a one-time token?

**Comment by hubertprein** [comment]
Is there any chance you could supply me with some request info from the `web` and `Electron` request? Hopefully there is some information in there, so we can differentiate between the two. So we can really add a proper `desktop` type and add a new `web` type as default.

Edit:
Is there any chance you could try a new branch I've created? Please look at this commit: https://github.com/hubertprein/Craft-JwtManager/commit/414b847eda7bfa9758a27c270aee59c3c45bbd95 and try the [web-desktop-type](https://github.com/hubertprein/Craft-JwtManager/tree/web-desktop-type) branch if you could.

**Comment by internetztube** [comment]
Thanks! I will check that later today.
